variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"

stages:
  - build
  - test
  - publish
  - deploy

maven-build:
  stage: build
  image: maven:3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS compile
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar

maven-test:
  stage: test
  image: maven:3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS test

maven-publish:
  stage: publish
  image: maven:3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS deploy

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script: ''
  script:
    - export KUBECONFIG=$KUBECONFIG
    - curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" "$NEXUS_URL/org/sonar/samples/openapi/dosonarapi-community/1.0.3/dosonarapi-community-1.0.3.jar" -o "dosonarapi-community-1.0.3.jar"
    - helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
    - helm repo update
    - helm upgrade --install -n sonarqube-dev sonarqube-lts-dev sonarqube/sonarqube-lts --create-namespace -f sonarqube/values-dev.yam
  needs:
    - "maven-publish"
  # only:
  #    refs:
  #     - /^[0-9]+(\.[0-9]+)+(\.[0-9]+)$/
