sonar.host.url=https://sonarcloud.io
sonar.organization=apiaddicts
sonar.projectKey=apiaddicts_sonaropenapi-rules
sonar.sources=.
sonar.exclusions=**/*.html,**/*.json
sonar.cpd.exclusions=**/*.html,**/*.json